# Build and test the Flutter project on push, only for the directory that were changed


name: Flutter build and test

on: push

env:
  FLUTTER_FOLDER: '$HOME/flutter'

jobs:
  pre-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Detect changed directories
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            dart_filter:
              - added|modified: '**/*.dart'
    outputs:
      changed-dirs: ${{ steps.filter.outputs.dart_filter_files }}
      skip: ${{ steps.filter.dart_filter }}

  build:
    runs-on: ubuntu-latest
    needs: [pre-run]
    if: needs.pre-run.outputs.skip == 'false'
    # Loop over 'needs.pre-run.outputs.changed-dirs' and run the following steps for each directory that were changed
    # The 'needs.pre-run.outputs.changed-dirs' is a string with the changed directories separated by a space
    # The 'needs.pre-run.outputs.changed-dirs' is empty if no directories were changed
    strategy:
      matrix:
        dir: ${{ needs.pre-run.outputs.changed-dirs }}

    steps:

      - uses: actions/checkout@v3

      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v3
        with:
          path: |
            flutter
            ~/.pub-cache

          key: flutter-${{ hashFiles('**/pubspec.lock') }}

      - if: ${{ steps.cache-flutter.outputs.cache-hit != 'true' }}
        name: Install Flutter
        run: git clone https://github.com/flutter/flutter.git --depth 1 -b stable $FOLDER

      - name: Add Flutter to PATH
        run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - if: ${{ steps.cache-flutter.outputs.cache-hit != 'true' }}
        name: Install dependencies
        run: flutter pub get --directory ${{ matrix.dir }}

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed ${{ matrix.dir }}/lib/** ${{ matrix.dir }}/test/**

      - name: Analyze project source
        run: flutter analyze --no-fatal-infos ${{ matrix.dir }}/lib/ ${{ matrix.dir }}/test/

      - name: Run tests
        run: |
          cd ${{ matrix.dir }}
          flutter test